"""Add edited_at to posts and replies

Revision ID: 67263caba1a4
Revises: 548b3efab761
Create Date: 2025-12-01 16:55:17.814933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67263caba1a4'
down_revision = '548b3efab761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('edited_at')

    # ### end Alembic commands ###
