"""Add image_url and gif_url to Post

Revision ID: aa849e331679
Revises: a0c7945d1b57
Create Date: 2025-11-29 02:39:33.015987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa849e331679'
down_revision = 'a0c7945d1b57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gif_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('gif_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_column('gif_url')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('gif_url')
        batch_op.drop_column('image_url')

    op.create_table('reactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=10), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name=op.f('unique_reaction'))
    )
    # ### end Alembic commands ###
