"""Add actor_id to notifications

Revision ID: c0c266a83e61
Revises: 67263caba1a4
Create Date: 2025-12-08 21:03:56.983274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c266a83e61'
down_revision = '67263caba1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('action_type', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(
            'fk_notifications_actor_id_users',  # <- give the constraint a name
            'users',
            ['actor_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('action_type')
        batch_op.drop_column('actor_id')

    # ### end Alembic commands ###
